# Python  TASK 2-b
## Name- Jatin Karthik
## Matriculation no.-313301

In [137]:
import csv
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

reading the CSV files from its location

In [2]:
store=pd.read_csv('D:\\Hildesheim Universitaet\\Semester 1\\ML LAB\\Excercise_2\\rossmann-store-sales\\store.csv')
#store.head()
sales=pd.read_csv('D:\\Hildesheim Universitaet\\Semester 1\\ML LAB\\Excercise_2\\rossmann-store-sales\\train.csv', low_memory=False )

In [6]:
#RI=sales[sales['Store'].value_counts()==942].index.tolist()
#RI=list(np.where(sales["Store"].value_counts()==942))


**a. Find all the stores that have sales recorded for 942 days**

In [131]:
f=sales.sort_values(by=["Store"])  #Sorting the train dataset w.r.t Store ID and getting 942 days of sales of every store together
f


Store  DayOfWeek        Date  Sales  Customers  Open  Promo  \
0            1          5  2015-07-31   5263        555     1      1   
766335       1          2  2013-08-13   5299        573     1      1   
951425       1          4  2013-02-28   4676        581     1      0   
372890       1          4  2014-08-07   4154        480     1      1   
373825       1          3  2014-08-06   5337        575     1      1   
...        ...        ...         ...    ...        ...   ...    ...   
375694    1115          2  2014-08-05   7028        459     1      1   
374759    1115          3  2014-08-06   5746        400     1      1   
373824    1115          4  2014-08-07   6616        451     1      1   
379434    1115          5  2014-08-01   8580        514     1      1   
1017208   1115          2  2013-01-01      0          0     0      0   

        StateHoliday  SchoolHoliday  
0                  0              1  
766335             0              1  
951425             0              0  
372890             0              1  
373825             0              1  
...              ...            ...  
375694             0              1  
374759             0              1  
373824             0              1  
379434             0              1  
1017208            a              1  

[1017209 rows x 9 columns]

In [58]:
f=f.pivot(index='Store',columns='Date',values='Sales') #Pivot is similar to transpose but with its own features wherein 
X=f.dropna() #we can change the column and the index as we wish
X



Date   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06  \
Store                                                                           
1             0.0      5530.0      4327.0      4486.0      4997.0         0.0   
2             0.0      4422.0      4159.0      4484.0      2342.0         0.0   
3             0.0      6823.0      5902.0      6069.0      4523.0         0.0   
4             0.0      9941.0      8247.0      8290.0     10338.0         0.0   
5             0.0      4253.0      3465.0      4456.0      1590.0         0.0   
...           ...         ...         ...         ...         ...         ...   
1111          0.0      5097.0      4579.0      4640.0      3325.0         0.0   
1112          0.0     10797.0      8716.0      9788.0      9513.0         0.0   
1113          0.0      6218.0      5563.0      5524.0      5194.0         0.0   
1114          0.0     20642.0     18463.0     18371.0     18856.0         0.0   
1115          0.0      3697.0      4297.0      4540.0      4771.0         0.0   

Date   2013-01-07  2013-01-08  2013-01-09  2013-01-10  ...  2015-07-22  \
Store                                                  ...               
1          7176.0      5580.0      5471.0      4892.0  ...      3464.0   
2          6775.0      6318.0      6763.0      5618.0  ...      5093.0   
3         12247.0      9800.0      8001.0      7772.0  ...      5414.0   
4         12112.0     10031.0      8857.0      9472.0  ...      8503.0   
5          6978.0      5718.0      5974.0      4999.0  ...      3595.0   
...           ...         ...         ...         ...  ...         ...   
1111       9444.0      6472.0      5307.0      5887.0  ...      4021.0   
1112      25165.0     17058.0     14724.0     14366.0  ...      6029.0   
1113       8984.0      6866.0      6115.0      7508.0  ...      4565.0   
1114      21237.0     18816.0     17073.0     18075.0  ...     20424.0   
1115       6905.0      5243.0      4649.0      5007.0  ...      5342.0   

Date   2015-07-23  2015-07-24  2015-07-25  2015-07-26  2015-07-27  2015-07-28  \
Store                                                                           
1          3769.0      3706.0      4364.0         0.0      6102.0      5011.0   
2          4108.0      3854.0      2512.0         0.0      6627.0      5671.0   
3          5702.0      5080.0      3878.0         0.0      8107.0      8864.0   
4          7286.0      8322.0      9322.0         0.0     11812.0     10275.0   
5          3713.0      3815.0      2030.0         0.0      7059.0      6083.0   
...           ...         ...         ...         ...         ...         ...   
1111       3587.0      3918.0      2177.0         0.0      7742.0      6793.0   
1112       6730.0      6220.0      6216.0         0.0     14383.0      9583.0   
1113       6410.0      6399.0      4784.0         0.0      7582.0      6468.0   
1114      20564.0     19627.0     21312.0         0.0     26720.0     25518.0   
1115       6150.0      5816.0      6897.0         0.0     10712.0      8093.0   

Date   2015-07-29  2015-07-30  2015-07-31  
Store                                      
1          4782.0      5020.0      5263.0  
2          6402.0      5567.0      6064.0  
3          7610.0      8977.0      8314.0  
4         10514.0     10387.0     13995.0  
5          5899.0      4943.0      4822.0  
...           ...         ...         ...  
1111       4907.0      5263.0      5723.0  
1112       9179.0      9652.0      9626.0  
1113       6640.0      7491.0      7289.0  
1114      25840.0     24395.0     27508.0  
1115       7661.0      8405.0      8680.0  

[934 rows x 942 columns]

In [62]:
R=np.array(X)
#R[:,941]
np.shape(R)

(934, 942)

As we can see, we got 934x942 matrix representing there are 934 such stores which have recorded sales for 942 days

In [114]:
store_uni=((sales['Store']).value_counts()==942).value_counts() #Value_counts returns the number of unique occurences
store_uni                                                       # This helps us re-verify that the matrix shape we got is correct

True     934
False    181
Name: Store, dtype: int64

**Create a data matrix of the shape (#_of_stores, 942) for the daily sales record of these stores**

**Use the first 800 stores in this data matrix for training and the rest for testing. Also split the 
sales data into 2 parts, the 1st part contains the information about the first 900 days of sales 
(these would be the features) and the 2nd contains the information about the last 42 days of 
sales (these would be the targets). The resultant matrices should be of the dimensions:**

In [115]:
print ("TRAINING SET")  #c part 
print("Xtrain.shape: ", X.iloc[0:800,0:900])  #Bifurcating Xtrain,Ytrain,Xtest and ytest
print("Ytrain.shape: ", X.iloc[0:800,0:42])

print("TESTING SET")
print("Xtest.shape: ", X.iloc[134,900])
print("Ytest.shape: ", X.iloc[134,42])
Xtrain = X.iloc[0:800,0:900]
Xtest = X.iloc[800:,0:900]
Ytrain = X.iloc[0:800,900:]
Ytest = X.iloc[800:,900:]

TRAINING SET
Xtrain.shape:  Date   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06  \
Store                                                                           
1             0.0      5530.0      4327.0      4486.0      4997.0         0.0   
2             0.0      4422.0      4159.0      4484.0      2342.0         0.0   
3             0.0      6823.0      5902.0      6069.0      4523.0         0.0   
4             0.0      9941.0      8247.0      8290.0     10338.0         0.0   
5             0.0      4253.0      3465.0      4456.0      1590.0         0.0   
...           ...         ...         ...         ...         ...         ...   
954           0.0      6470.0      5914.0      5343.0      6811.0         0.0   
955           0.0      2942.0      3222.0      2810.0      3200.0         0.0   
956           0.0      4072.0      4059.0      3424.0      2337.0         0.0   
957           0.0      6854.0      5977.0      6318.0      4913.0         0.0   


**Iteratively build multiple linear regression models for column vectors of 𝑌𝑡𝑟𝑎𝑖𝑛. You are 
allowed to use the numpy routines for calculating inverses, transposing of matrices and 
matrix multiplication. You would need to create 42 models in this case (1 model for each day 
in the target sales matrix)**

In [116]:
beta = np.linalg.inv(Xtrain.T.dot(Xtrain)).dot(Xtrain.T).dot(Ytrain)
print(beta)
print(np.shape(beta))

[[ 1.07249248e+05  1.63845280e+05  1.31187273e+05 ...  1.43679278e+05
   1.48264968e+05  1.68739973e+05]
 [ 2.21446826e+01  3.42028050e+01  2.78466059e+01 ...  3.09975385e+01
   3.18620749e+01  3.55673899e+01]
 [-6.50510455e-01 -1.04305342e+00 -9.64333167e-01 ... -1.33384491e+00
  -9.50619771e-01 -1.32303712e+00]
 ...
 [-2.36734204e-01 -7.07725626e-10  8.91897015e-02 ...  3.15155801e-01
   1.54419170e-01 -4.37607776e-01]
 [ 6.68170532e-02 -1.52873814e-09 -2.26316136e-01 ...  9.48066571e-02
   6.96603082e-01  8.61199198e-02]
 [ 2.06369035e-01  9.69483542e-10  3.60789806e-01 ... -3.09873292e-01
   3.14630601e-01  6.27760122e-01]]
(900, 42)


**Verify that you have learned 𝛽0:900 for each of the 42 models and use these learned 
parameters to make predictions for each day ahead. In total 42 days.**

In [117]:
#Y_pred=np.matmul(Xtrain,beta)
#A=(Xtrain.T).dot(Xtrain)
#B=(Xtrain.T).dot(Ytrain)
B_nm= np.linalg.lstsq(Xtrain,Ytrain,rcond=None)[0]
np.shape(B_nm)

(900, 42)

In [146]:
#y_predicted=np.linalg.inv(Xtest.T.dot(Xtest)).dot(Xtest.T).dot(Ytest)
y_predicted=np.dot(Xtest,beta)
y_predicted

array([[ 23532.93246282,  28615.5096775 ,  29360.47792768, ...,
         27568.07869033,  29175.807471  ,  33498.56341511],
       [ 11920.20996181,   3796.63959206,   9260.076258  , ...,
          5846.77820148,   7110.20847831,  10415.76754917],
       [ 25902.53093247,  41366.09444633,  41787.74141627, ...,
         41715.86793083,  39496.56943145,  47218.65722303],
       ...,
       [-22797.22054898, -44890.82046839, -29795.30937531, ...,
        -28774.26621924, -33519.61396715, -40131.04943876],
       [ 62916.88892569,  59180.77600069,  65160.46808906, ...,
         61388.56531335,  81797.94746527,  91124.04245921],
       [-27272.90929137, -53882.37049743, -36356.89834974, ...,
        -38312.75383778, -33016.37851888, -42842.37598718]])

**Calculate and print the daily RMSE and MAE for all 42 sales values using test split (𝑋𝑡𝑒𝑠𝑡 as 
input). Also calculate and print overall average RMSE and MAE. (i.e. just the mean RMSE of 
all 42 models).**

In [10]:
RMSE=np.sqrt(((y_predicted - Ytest) ** 2).mean())

In [100]:
RMSE

Date
2015-06-20    4.500803e+07
2015-06-21    4.418698e+07
2015-06-22    5.159687e+07
2015-06-23    4.836825e+07
2015-06-24    4.807847e+07
2015-06-25    4.767183e+07
2015-06-26    5.139752e+07
2015-06-27    4.699584e+07
2015-06-28    4.559136e+07
2015-06-29    7.515051e+07
2015-06-30    7.476810e+07
2015-07-01    6.654663e+07
2015-07-02    6.448501e+07
2015-07-03    6.528130e+07
2015-07-04    4.712455e+07
2015-07-05    4.668295e+07
2015-07-06    5.845787e+07
2015-07-07    5.117185e+07
2015-07-08    5.362384e+07
2015-07-09    5.294882e+07
2015-07-10    5.429587e+07
2015-07-11    4.724215e+07
2015-07-12    4.807128e+07
2015-07-13    7.196686e+07
2015-07-14    6.526766e+07
2015-07-15    6.289979e+07
2015-07-16    6.148373e+07
2015-07-17    6.093334e+07
2015-07-18    4.953491e+07
2015-07-19    5.032807e+07
2015-07-20    5.617669e+07
2015-07-21    5.055855e+07
2015-07-22    4.955323e+07
2015-07-23    5.170538e+07
2015-07-24    5.206494e+07
2015-07-25    4.521862e+07
2015-07-26    4.854529e

In [18]:
MAE= (abs(y_predicted - Ytest).mean())
MAE

Date
2015-06-20    7.472416e+06
2015-06-21    7.595946e+06
2015-06-22    8.617055e+06
2015-06-23    8.075165e+06
2015-06-24    8.022684e+06
2015-06-25    7.959601e+06
2015-06-26    8.591372e+06
2015-06-27    7.811951e+06
2015-06-28    7.841867e+06
2015-06-29    1.236596e+07
2015-06-30    1.234934e+07
2015-07-01    1.105615e+07
2015-07-02    1.072666e+07
2015-07-03    1.087555e+07
2015-07-04    7.837386e+06
2015-07-05    8.033244e+06
2015-07-06    9.704882e+06
2015-07-07    8.522972e+06
2015-07-08    8.933829e+06
2015-07-09    8.815662e+06
2015-07-10    9.063286e+06
2015-07-11    7.855790e+06
2015-07-12    8.274304e+06
2015-07-13    1.186682e+07
2015-07-14    1.082801e+07
2015-07-15    1.043803e+07
2015-07-16    1.021680e+07
2015-07-17    1.016218e+07
2015-07-18    8.235649e+06
2015-07-19    8.668316e+06
2015-07-20    9.319167e+06
2015-07-21    8.415214e+06
2015-07-22    8.259091e+06
2015-07-23    8.587073e+06
2015-07-24    8.688199e+06
2015-07-25    7.513596e+06
2015-07-26    8.359178e

**Use the following approaches and report the overall average RMSE and MAE for them:
i. Repeating last sale value per store: Use the last recorded sales value of each store 
and repeat it for the next 42 days**

In [125]:
future_sale=[]           #Taking the sales of the last column i.e the last recorded sales in the dataset
future_sale1=[]
for i in range(0,934):
    
        future_sale.append(R[i,941])
        future_sale1.append(R[i,941])   #concatenating it to create a y_predict dataset called repeat_sales
np.shape(future_sale)

for j in range(0,41):
    future_sale=np.vstack((future_sale,future_sale1))

repeat_sale=future_sale.T[800:,:42]    #slicing it to match the dimensions of Y_test to find RMSE
#np.shape(future_sale.T)

RMSE2=(np.sqrt(((repeat_sale - Ytest) ** 2).mean())).mean()  #since overallaverage RMSE and MAE is asked, so mean twice
print("Overall RMSE is",RMSE2)
MAE2= (abs(repeat_sale - Ytest).mean()).mean()
print("Overall MAE is",MAE2)


Overall RMSE is 3898.592909296811
Overall MAE is 3532.9797441364603


**Repeating mean value per store: Repeat the mean of sales for the sales horizon.**

In [129]:
mean_sale=[]
mean_sale1=[]
for i in range(0,934):
    mean_sale.append(R[i].mean())
    mean_sale1.append(R[i].mean())
    
for j in range(0,41):
    mean_sale=np.vstack((mean_sale,mean_sale1))
    
mean_repeat_sale=mean_sale.T[800:,:42]    #slicing it to match the dimensions of Y_test to find RMSE
#np.shape(future_sale.T)

RMSE3=(np.sqrt(((mean_repeat_sale - Ytest) ** 2).mean())).mean()  #since overallaverage RMSE and MAE is asked, so mean twice
print("Overall RMSE is",RMSE3)
MAE3= (abs(mean_repeat_sale - Ytest).mean()).mean()
print("Overall MAE is",MAE3)


Overall RMSE is 2501.958231469882
Overall MAE is 2214.525431682956


**Repeating mean value per store per weekday: For each of the 42 days ahead get 
their predictions as a mean of all sales recorded for that day of week in the past. For 
e.g., the prediction of Monday ahead should be the mean of all sales for this 
particular store on all previous Mondays.**

In [135]:
#from statistics import mean
f
Mon=f[(f["DayOfWeek"]==1) & (f["Store"]==1)]['Sales'].mean()


4946.119402985075

Linear regression is usally a good choice for prediction tasks wherein already pre-existing data is available based on which we need to predict the future values. But, in this case since the only type of features we are utilising are sales and not considering other aspects like Open or close and customers etc. this model degenerates. Therefore, in my opinion even though Linear regression as an algorithm is good for prediction tasks but with various kinds of features of different categories; it doesn't function properly.

References used:-
https://www.youtube.com/watch?v=r89yH82OAFw
https://medium.com/machine-learning-with-python/multiple-linear-regression-implementation-in-python-2de9b303fc0c
https://medium.com/analytics-vidhya/multiple-linear-regression-from-scratch-using-only-numpy-98fc010a1926
https://www.youtube.com/watch?v=T0PRiF7X__g

https://stackoverflow.com/questions/33907776/how-to-create-an-array-of-dataframes-in-python
